import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

// The root package.json's "version" is the single source of truth for the
// installed product version — everything downstream that needs it is
// generated from here instead of being a second, hand-kept-in-sync literal
// (packages/shared/src/shared.constants.ts's APP_VERSION used to be exactly
// that, with a comment admitting it). Runs automatically before every root
// `npm run build` (see package.json's `prebuild`).
const rootDir = join(dirname(fileURLToPath(import.meta.url)), '..');

export function syncVersion() {
  const rootPackageJson = JSON.parse(readFileSync(join(rootDir, 'package.json'), 'utf-8'));
  const version = rootPackageJson.version;
  if (!/^\d+\.\d+\.\d+$/.test(version)) {
    throw new Error(`Root package.json version "${version}" isn't a plain semver x.y.z — sync targets assume that shape.`);
  }

  const sharedConstantsPath = join(rootDir, 'packages', 'shared', 'src', 'shared.constants.ts');
  const sharedConstants = readFileSync(sharedConstantsPath, 'utf-8');
  const appVersionPattern = /export const APP_VERSION = '[^']*';/;
  if (!appVersionPattern.test(sharedConstants)) {
    throw new Error(`Could not find APP_VERSION in ${sharedConstantsPath} — update sync-version.js's pattern to match.`);
  }
  writeFileSync(
    sharedConstantsPath,
    sharedConstants.replace(appVersionPattern, `export const APP_VERSION = '${version}';`),
  );

  // Generated include for portixone.iss (`#include "version.iss"`) — not
  // hand-edited, not committed (see .gitignore), regenerated by this script.
  writeFileSync(
    join(rootDir, 'installer', 'version.iss'),
    `; Generated by scripts/sync-version.js from the root package.json's "version" — do not edit by hand.\n#define MyAppVersion "${version}"\n`,
  );

  return version;
}

const isMainModule = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMainModule) {
  const version = syncVersion();
  console.log(`Synced version ${version} -> packages/shared/src/shared.constants.ts, installer/version.iss`);
}
